name: Nasa project
on:
  push:
    branches: [ master ]
  pull-request:
    branches: [ master ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: setting up node
        uses: action/setup-node@v3
        with:
          node-version: "22"
      - run: npm install
      - run: npm run build --prefix client

