name: Nasa project
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build:
    env: 
     CI: true
     MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        mongodb-version: [ '6.0', '8.0' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setting up node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: mongodb in github actions
        uses: supercharge/mongodb-github-action@1.11.0
      - run: npm install
      - run: npm run build --prefix client

